import { Command } from "commander";
import { existsSync, statSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { CliRuntime } from "../helpers.js";
import { run, printJson } from "../helpers.js";

// --- Skill content ---

// BEGIN SKILL_FILES — generated by scripts/sync-skills.cjs. Do not edit by hand;
// edit skills/seclai-cli/ and run `npm run sync:skills`.
const SKILL_FILES: Array<{ name: string; content: string }> = [
  { name: "SKILL.md", content: `---
name: seclai-cli
description: >-
  Manage Seclai agents, knowledge bases, sources, memory banks, evaluations,
  solutions, governance, alerts, agent email, and models via the CLI. Use when
  working with the Seclai platform or when the user mentions Seclai CLI commands.
---

# Seclai CLI

The Seclai CLI (\`seclai\` / \`npx @seclai/cli\`) manages agents, knowledge bases,
sources, memory banks, evaluations, solutions, governance, alerts, agent email,
and models from the terminal.

Every command writes JSON to stdout. Pipe into \`jq\` for filtering. Errors go to
stderr and set a non-zero exit code, so \`set -e\` scripts fail as expected.

**Find the commands for a task in the map below, then read that reference file.**
Only this page is loaded up front; the references are read on demand.

## Quick start

\`\`\`bash
export SECLAI_API_KEY="sk-..."

seclai agents create --json '{"name":"My Agent","description":"QA chatbot"}'
seclai agents ai gen-steps <agentId> --user-input "Build a QA chatbot that uses a knowledge base"
seclai agents ai mark <agentId> <conversationId> --json '{"accepted":true}'
seclai agents run <agentId> --json '{"input":"How do I reset my password?"}' --stream
seclai agents runs list <agentId>
\`\`\`

## Command map

| Group | What it covers | Reference |
| --- | --- | --- |
| \`agents\` | Agents, runs, definitions, export/import, input uploads, triggers, agent AI | [references/agents.md](references/agents.md) |
| \`sources\` \`contents\` \`kb\` \`memory\` | Sources and uploads, exports, embedding migration, indexed content, knowledge bases, memory banks | [references/knowledge.md](references/knowledge.md) |
| \`evals\` | Evaluation criteria, results, runs, agent-level summaries | [references/evaluations.md](references/evaluations.md) |
| \`solutions\` \`governance\` | Solutions, resource links, conversations, solution and governance AI | [references/solutions.md](references/solutions.md) |
| \`alerts\` | Alerts, alert configurations, organization preferences | [references/alerts.md](references/alerts.md) |
| \`email\` | Agent email: sending domains, inbound blocklist, inbound health, opt-outs | [references/email.md](references/email.md) |
| \`models\` | Model catalog, generation tiers, model alerts, recommendations, playground experiments | [references/models.md](references/models.md) |
| \`auth\` \`configure\` \`api-version\` \`mcp\` \`skills\` \`completion\` | Authentication, profiles, API version pinning, editor integration | [references/setup.md](references/setup.md) |
| \`ai\` | Top-level AI assistant for knowledge bases, sources, solutions and memory | [references/ai-assistant.md](references/ai-assistant.md) |
| \`search\` \`docs\` \`me\` | Search across resources, search the documentation, show the authenticated account | below, under [Search and account](#search-and-account) |

Cross-cutting topics: [streaming and event modes](references/streaming.md),
[file uploads](references/uploads.md).

## Authentication

Two modes:

1. **API key** — set \`SECLAI_API_KEY\`, or pass \`--api-key <key>\`.
2. **SSO** — \`seclai auth login\` for browser-based OAuth2/PKCE. Tokens are cached
   locally and refreshed automatically.

Override the API host with \`SECLAI_API_URL\` (default \`https://api.seclai.com\`).

## Global options

\`\`\`bash
--api-key <key>              # or set SECLAI_API_KEY
--profile <name>             # SSO profile (or SECLAI_PROFILE, default 'default')
--account-id <id>            # multi-org targeting (X-Account-Id header)
--config-dir <path>          # or SECLAI_CONFIG_DIR, default ~/.seclai
--api-version <date>         # or SECLAI_API_VERSION; see below
--allow-unknown-api-version  # send a version this CLI was not built against
--compact                    # single-line JSON
-V, --version
\`\`\`

## API versions

The API is versioned by date, and a version can change a response's shape — a
bare array becoming \`{data, pagination}\`, for instance. **The CLI sends no
version header by default**, so upgrading it never changes what a command
prints. Opt in per invocation, or pin the account:

\`\`\`bash
seclai api-version get                        # what does a request resolve to?
seclai --api-version 2026-07-27 alerts list   # this invocation only
seclai api-version set 2026-07-27             # every client on the account
seclai api-version clear
\`\`\`

An \`--api-version\` this CLI was not built against is rejected, because a newer
version can reshape a response the CLI would then misread. Pass
\`--allow-unknown-api-version\` to send it anyway. \`api-version set\` takes a
\`YYYY-MM-DD\` date and rejects anything else, because the pin applies to every
client on the account.

\`--api-key\`, \`--profile\`, \`--account-id\` and \`--config-dir\` reject an empty
value. A shell expanding an unset variable passes \`""\`, which the SDK's
credential chain discards, so each would silently resolve elsewhere — a
different identity, another account's cached tokens, or the default org. Guard
the flag rather than the value: \`seclai \${KEY:+--api-key "\$KEY"} agents list\`.

An empty \`--api-version\` is accepted with a warning, since it costs only the
version header; a future release will reject it too.

## Common patterns

**JSON input.** Most create/update commands take \`--json '{"key":"value"}'\` or
\`--json-file path.json\`. Use \`-\` as the value to read from stdin.

**AI shorthand.** AI generation commands accept \`--user-input <text>\` in place of
\`--json '{"user_input":"<text>"}'\`.

**Pagination.** List commands take \`--page <n>\` and \`--limit <n>\`; some add
\`--sort <field>\` and \`--order asc|desc\`. A few endpoints paginate by offset
instead and take \`--limit\` / \`--offset\`.

**Uploads.** Upload commands take \`--file <path>\`, plus optional \`--title\`,
\`--metadata '{"k":"v"}'\`, \`--metadata-file\`, \`--file-name\` and \`--mime-type\`.

## Search and account

\`\`\`bash
seclai search --query "deployment guide" [--limit N] [--entity-type <type>]
seclai docs search --query "memory banks" [--mode keyword|semantic] [--limit N]
seclai me   # account ID and organization memberships
\`\`\`
` },
  { name: "references/agents.md", content: `# Agents

Agents, their runs, definitions, export/import, input uploads, triggers, and the
agent AI assistant.

## CRUD and lifecycle

\`\`\`bash
seclai agents list [--page N] [--limit N]
seclai agents create --json '{"name":"My Agent","description":"..."}'
seclai agents get <agentId>
seclai agents update <agentId> --json '{"name":"Renamed"}'
seclai agents delete <agentId>

# pause across every trigger path (API, schedule, email, sub-agent calls)
seclai agents disable <agentId>
seclai agents enable <agentId>

# which live agents call this one via a call_agent step?
seclai agents callers <agentId>
\`\`\`

## Triggers

\`\`\`bash
# alias, sender allowlist and inbound-handling flags for an EMAIL_RECEIVED trigger
seclai agents triggers email-config <agentId> <triggerId> --json '{"alias":"support"}'
\`\`\`

## Running agents

Four modes: basic, streaming, NDJSON events, and polling. See
[streaming.md](streaming.md) for event shapes and filtering.

\`\`\`bash
# simple run — returns the final result
seclai agents run <agentId> --json '{"input":"Hello"}'

# stream — wait for completion via SSE, print the final result
seclai agents run <agentId> --json '{"input":"Hello"}' --stream [--timeout-ms 60000]

# events — every SSE event as an NDJSON line
# --output: full (entire event), data (event data only), status (one-line summary)
# --event-filter: comma-separated event types, e.g. "status,data"
seclai agents run <agentId> --json '{"input":"Hello"}' --events [--output full|data|status] [--event-filter "status,data"]

# poll — submit, then poll until complete
seclai agents run <agentId> --json '{"input":"Hello"}' --poll [--poll-interval-ms 2000] [--include-step-outputs]
\`\`\`

## Runs

\`\`\`bash
seclai agents runs list <agentId> [--page N] [--limit N] [--status <status>]
seclai agents runs get <runId> [--include-step-outputs]
seclai agents runs cancel <runId>
seclai agents runs delete <runId>  # deprecated alias for \`runs cancel\`; the API has no delete-a-run operation
seclai agents runs search --json '{"query":"..."}'
seclai agents runs eval-results <agentId> <runId> [--page N] [--limit N]

# Download a file emitted by a run step. attachmentId is the URL-safe-base64
# storage_key from run output manifests or webhooks.
seclai agents runs download-attachment <runId> <attachmentId> [--download-name <name>] [--output <path>]
\`\`\`

Without \`--output\`, raw bytes go to stdout — redirect to a file rather than
letting them hit the terminal.

## Definitions

\`\`\`bash
seclai agents def get <agentId>
seclai agents def update <agentId> --json '{"steps":[{"step_type":"llm","config":{}}]}'
\`\`\`

## Export and import

\`\`\`bash
# portable JSON snapshot of an agent definition
seclai agents export <agentId> [--no-download]

# Validate an agent_definition payload before importing — no writes.
# Reports counts and any unresolved_refs (knowledge bases, memory banks, source
# connections or sub-agents that do not exist in this account).
seclai agents export <agentId> \\
  | jq '{agent_definition: .}' \\
  | seclai agents preview-import --json-file -

# Import via \`agents create\` (or \`agents update\`) with agent_definition set to
# the export payload, and entity_remap mapping unresolved source UUIDs to target
# UUIDs taken from preview-import's unresolved_refs[*].alternatives.
seclai agents create --json '{"name":"Imported","trigger_type":"dynamic_input","agent_definition":{},"entity_remap":{}}'
\`\`\`

## Input uploads

\`\`\`bash
# What files (if any) does this agent expect? requires_uploads reports whether it
# accepts files; the agent block lists the names, indexes and patterns a run-time
# batch must satisfy. Call this before staging uploads.
seclai agents attachment-references <agentId>

seclai agents upload-input <agentId> --file ./input.pdf [--file-name name] [--mime-type type]
seclai agents input-status <agentId> <uploadId>
\`\`\`

## Agent AI assistant

\`\`\`bash
seclai agents ai gen-steps <agentId> --user-input "Build a QA chatbot"
seclai agents ai step-config <agentId> --json '{"step_type":"llm","user_input":"Configure the LLM step"}'

# --step-type is required; the API rejects the request without it
seclai agents ai history <agentId> --step-type llm [--step-id <id>] [--limit N] [--offset N]

seclai agents ai mark <agentId> <conversationId> --json '{"accepted":true}'
\`\`\`

## Example: knowledge-base-backed agent

\`\`\`bash
seclai kb create --json '{"name":"Support KB","description":"Customer support articles"}'
seclai agents create --json '{"name":"Support Bot","description":"Answers customer questions"}'
seclai agents ai gen-steps <agentId> --user-input "Build a QA chatbot that searches the Support KB"
seclai agents ai mark <agentId> <conversationId> --json '{"accepted":true}'
seclai agents run <agentId> --json '{"input":"How do I reset my password?"}' --stream
\`\`\`

## Example: memory-powered agent

\`\`\`bash
seclai memory create --json '{"name":"User Preferences","type":"general"}'
seclai agents create --json '{"name":"Personal Assistant","description":"Remembers user preferences"}'
seclai agents ai gen-steps <agentId> --user-input "Build a chat agent that remembers user preferences. Use general memory bank <memoryBankId>"
seclai agents ai mark <agentId> <conversationId> --json '{"accepted":true}'
\`\`\`
` },
  { name: "references/ai-assistant.md", content: `# Top-level AI assistant

\`seclai ai\` creates resources from a natural-language description, without
starting from a solution or an agent. The domain-scoped assistants —
\`agents ai\`, \`memory ai\`, \`solutions ai\`, \`governance ai\` — live with their
resources.

\`\`\`bash
seclai ai kb --user-input "Create a support knowledge base"
seclai ai source --user-input "Create a documentation source"
seclai ai solution --user-input "Build a customer support solution"
seclai ai memory --user-input "Create a conversation memory bank"

seclai ai memory-history
seclai ai accept <conversationId> --json '{"accepted":true}'
seclai ai decline <conversationId>
seclai ai memory-accept <conversationId> --json '{"accepted":true}'

seclai ai feedback --json '{"feedback":"The response was helpful"}'
\`\`\`

## The generate-then-accept cycle

Every assistant command returns a *proposal* with a conversation ID. Nothing is
created until you accept it:

\`\`\`bash
seclai ai kb --user-input "Create a support knowledge base"
# read the proposal, note the conversation id
seclai ai accept <conversationId> --json '{"accepted":true}'
\`\`\`

Memory-bank proposals have their own accept command (\`ai memory-accept\`) and
their own history (\`ai memory-history\`); everything else uses \`ai accept\` /
\`ai decline\`.
` },
  { name: "references/alerts.md", content: `# Alerts

Account alerts, the configurations that raise them, and per-organization
delivery preferences.

Model-catalog alerts are separate — see [models.md](models.md).

## Alerts

\`\`\`bash
seclai alerts list [--page N] [--limit N] [--status <status>]
seclai alerts get <alertId>
seclai alerts status <alertId> --json '{"status":"resolved"}'
seclai alerts comment <alertId> --json '{"comment":"Fixed the issue"}'
seclai alerts subscribe <alertId>
seclai alerts unsubscribe <alertId>
\`\`\`

\`GET /alerts\` declares no severity filter, so there is no \`--severity\` — it
never filtered anything, and returned unfiltered rows that looked filtered.
Filter client-side instead:

\`\`\`bash
seclai alerts list | jq '[.data[] | select(.severity == "high")]'
\`\`\`

## Alert configurations

\`\`\`bash
seclai alerts configs list [--page N] [--limit N]
seclai alerts configs create --json '{"name":"Latency Alert","description":"...","threshold":5000}'
seclai alerts configs get <configId>
seclai alerts configs update <configId> --json '{"threshold":3000}'
seclai alerts configs delete <configId>
\`\`\`

## Organization preferences

\`\`\`bash
seclai alerts prefs list
seclai alerts prefs update <organizationId> <alertType> --json '{"enabled":true}'
\`\`\`

Preferences are per organization and per alert type, so \`update\` takes both.
` },
  { name: "references/email.md", content: `# Agent email

The domains agents send from, the inbound blocklist, inbound health, and
recipient opt-outs.

Per-agent inbound configuration (alias, sender allowlist) lives on the trigger —
see \`agents triggers email-config\` in [agents.md](agents.md).

## Sending domains

\`\`\`bash
seclai email domains list
seclai email domains add --kind custom --value mail.example.com [--delegated]
seclai email domains verify <domainId>        # run a DNS check now
seclai email domains set-primary <domainId>
seclai email domains test-email <domainId>    # send a test to the account owner
seclai email domains dmarc <domainId> [--days N] [--top-sources N]
seclai email domains remove <domainId>
seclai email domains use-shared               # revert to agent.seclai.com
\`\`\`

\`--kind\` is \`vanity\` (a subdomain of seclai.com) or \`custom\` (your own domain).
\`add\` returns the DNS records to publish; pass \`--delegated\` when the domain's
DNS is delegated to Seclai so those records are published for you. A domain must
verify before \`set-primary\` will accept it.

## Inbound sender blocklist

\`\`\`bash
seclai email blocked list [--limit N] [--offset N]
seclai email blocked add --sender-email spam@example.com [--note "phishing"]
seclai email blocked add --sender-email example.com --match-type domain
seclai email blocked remove <blockedId>
seclai email blocked auto-block-mode disabled|input|input_and_output
\`\`\`

\`--match-type\` is \`address\` (the default) or \`domain\`. \`auto-block-mode\` controls
whether a governance BLOCK on an authenticated sender adds them to the blocklist
automatically.

## Inbound health

\`\`\`bash
seclai email inbound status          # quota usage, pause state, queued run counts
seclai email inbound rejections [--agent-id <id>] [--limit N]
seclai email inbound cancel-queued   # fail every over-quota parked run at once
seclai email inbound resume          # lift the account-wide pause
\`\`\`

When inbound email exceeds quota, runs park in a QUEUED state and the account
pauses. \`status\` shows both; \`cancel-queued\` clears the backlog and \`resume\`
lifts the pause. Check \`rejections\` first — it reports why messages were turned
away, which is usually the more useful answer.

## Recipient opt-outs

\`\`\`bash
seclai email optouts list [--agent-id <id>] [--limit N] [--offset N]
seclai email optouts remove <optoutId>
\`\`\`

Removing an opt-out lets that recipient receive agent email again.
` },
  { name: "references/evaluations.md", content: `# Evaluations Workflow

## Step 1: Create evaluation criteria for an agent
\`\`\`bash
seclai evals criteria create <agentId> --json '{"name":"Answer Accuracy","description":"Does the answer correctly address the question?","eval_type":"llm_judge"}'
\`\`\`

## Step 2: Find runs to evaluate
\`\`\`bash
# list all runs for an agent
seclai agents runs list <agentId> --limit 10

# or find runs compatible with specific criteria
seclai evals compatible-runs <criteriaId> --limit 10
\`\`\`

## Step 3: Test criteria before committing
\`\`\`bash
seclai evals test-draft <agentId> --json '{"criteria":{"name":"Answer Accuracy","eval_type":"llm_judge","description":"..."},"run_id":"<runId>"}'
\`\`\`

## Step 4: Create evaluation results
\`\`\`bash
seclai evals results create <criteriaId> --json '{"run_id":"<runId>","score":0.95}'
\`\`\`

## Step 5: Review summaries
\`\`\`bash
seclai evals criteria summary <criteriaId>
seclai evals agent-results <agentId>
seclai evals agent-runs <agentId> --limit 20
seclai evals non-manual-summary <agentId>
\`\`\`

## Managing criteria
\`\`\`bash
seclai evals criteria list <agentId> [--page N] [--limit N] [--paged]
seclai evals criteria get <criteriaId>
seclai evals criteria update <criteriaId> --json '{"name":"Updated Name"}'
seclai evals criteria delete <criteriaId>
\`\`\`

\`--paged\` wraps the results in \`{"data": [...]}\` instead of returning a bare
array, so \`.data\` is a stable path to read whatever \`--api-version\` is in effect.
Nothing is invented: the \`pagination\` block appears only once the API sends one,
from \`--api-version 2026-07-27\`. Move scripts to \`.data\` first, then opt in to
get \`.pagination\`.

## Viewing results
\`\`\`bash
seclai evals results list <criteriaId> [--page N] [--limit N]
seclai evals compatible-runs <criteriaId> [--page N] [--limit N]
seclai evals agent-results <agentId> [--page N] [--limit N]
seclai evals agent-runs <agentId> [--page N] [--limit N]
\`\`\`
` },
  { name: "references/knowledge.md", content: `# Sources, content, knowledge bases and memory banks

The ingestion side of Seclai: where documents come from, how they are indexed,
and the stores agents read from.

For upload mechanics — MIME types, size limits, metadata — see
[uploads.md](uploads.md).

## Sources

\`\`\`bash
seclai sources list [--page N] [--limit N] [--sort field] [--order asc|desc] [--account-id id]
seclai sources create --json '{"name":"Docs","description":"Product documentation"}'
seclai sources get <sourceId>
seclai sources update <sourceId> --json '{"name":"Updated Docs"}'
seclai sources delete <sourceId>
\`\`\`

\`source\` is accepted as an alias for \`sources\`.

## Source uploads

\`\`\`bash
seclai sources upload <sourceId> --file ./doc.pdf [--title "My Doc"] [--metadata '{"category":"docs"}'] [--file-name name] [--mime-type type]
seclai sources upload-text <sourceId> --json '{"text":"Article content here...","title":"My Article"}'
\`\`\`

## Source exports

\`\`\`bash
seclai sources exports list <sourceId> [--page N] [--limit N]
seclai sources exports create <sourceId> --json '{"format":"jsonl"}'
seclai sources exports get <sourceId> <exportId>
seclai sources exports cancel <sourceId> <exportId>
seclai sources exports delete <sourceId> <exportId>
seclai sources exports download <sourceId> <exportId>
seclai sources exports estimate <sourceId> --json '{"format":"jsonl"}'
\`\`\`

\`estimate\` reports the size and cost before you commit to \`create\`.

## Embedding migration

\`\`\`bash
seclai sources migration get <sourceId>
seclai sources migration start <sourceId> --json '{"target_model":"text-embedding-3-large"}'
seclai sources migration cancel <sourceId>
\`\`\`

## Contents (indexed content)

\`\`\`bash
seclai contents get <contentVersionId> [--start N] [--end N]
seclai contents delete <contentVersionId>
seclai contents upload <contentVersionId> --file ./updated.pdf [--title "Title"] [--file-name name] [--mime-type type]
seclai contents replace-text <contentVersionId> --json '{"text":"Replacement text","title":"Updated"}'
seclai contents embeddings <contentVersionId> [--page N] [--limit N]
\`\`\`

\`--start\` / \`--end\` on \`contents get\` slice the returned text by character
offset, which is how you inspect a long document without pulling all of it.

## Knowledge bases

\`\`\`bash
seclai kb list [--page N] [--limit N] [--sort field] [--order asc|desc]
seclai kb create --json '{"name":"Support KB","description":"Customer support articles"}'
seclai kb get <kbId>
seclai kb update <kbId> --json '{"name":"Updated KB"}'
seclai kb delete <kbId>
\`\`\`

## Memory banks

\`\`\`bash
seclai memory list [--page N] [--limit N] [--sort field] [--order asc|desc]
# type: "conversation" (chat history) or "general" (structured facts)
seclai memory create --json '{"name":"Chat Memory","type":"conversation"}'
seclai memory get <memoryBankId>
seclai memory update <memoryBankId> --json '{"name":"Renamed"}'
seclai memory delete <memoryBankId>
\`\`\`

### Utilities

\`\`\`bash
seclai memory stats <memoryBankId>
seclai memory agents <memoryBankId>        # agents using this bank
seclai memory compact <memoryBankId>
seclai memory delete-source <memoryBankId>
seclai memory templates
seclai memory test-compaction <memoryBankId> --json '{"prompt":"Summarize the conversation"}'
seclai memory test-compaction-standalone --json '{"prompt":"Summarize the conversation"}'
\`\`\`

Both \`test-compaction\` commands are dry runs — they show what compaction would
produce without writing to the bank.

### Memory bank AI

\`\`\`bash
seclai memory ai generate --user-input "Configure compaction for chat memory"
seclai memory ai last
seclai memory ai accept <conversationId> --json '{"accepted":true}'
\`\`\`

## Example: create a source and upload content

\`\`\`bash
seclai sources create --json '{"name":"Product Docs","description":"Product documentation source"}'
# note the id from the output
seclai sources upload <sourceId> --file ./docs.pdf --title "Product Manual" --metadata '{"version":"2.0"}'
seclai sources get <sourceId>
\`\`\`
` },
  { name: "references/models.md", content: `# Models

The model catalog, media-generation tiers, model-catalog alerts, recommendations
and the playground.

## Catalog

\`\`\`bash
seclai models list [--provider <name>] [--supports-tool-use] [--supports-thinking]
seclai models list [--supports-input-media <media>] [--supports-output-media <media>]
seclai models get <modelId>

# each media-generation modality and tier, with its model and cost
seclai models tiers
\`\`\`

The capability flags compose, so \`--supports-tool-use --supports-thinking\`
returns only models with both. \`--supports-input-media\` / \`--supports-output-media\`
take a modality such as \`image\`, \`audio\` or \`video\`.

## Model alerts

\`\`\`bash
seclai models alerts list [--page N] [--limit N]
seclai models alerts mark-read <alertId>
seclai models alerts mark-all-read
seclai models alerts unread-count
\`\`\`

These are catalog alerts — deprecations, price changes, new models — not the
account alerts in [alerts.md](alerts.md).

## Recommendations

\`\`\`bash
seclai models recommendations <modelId>
\`\`\`

Suggests replacements for a model, which is how you act on a deprecation alert.

## Playground experiments

\`\`\`bash
seclai models experiments list [--days N] [--start-date <date>] [--end-date <date>] [--limit N] [--offset N]
seclai models experiments create --json '{"model_ids":["gpt-4o"],"prompt":"Compare responses"}'
seclai models experiments get <experimentId>
seclai models experiments cancel <experimentId>
seclai models experiments delete <experimentId>  # soft-delete, preserves audit history
\`\`\`

\`create\` takes several \`model_ids\` and runs the same prompt against each, which
is the point — side-by-side comparison. \`cancel\` stops a running experiment;
\`delete\` soft-deletes a finished one.
` },
  { name: "references/setup.md", content: `# Setup: authentication, profiles, API version, editor integration

## SSO authentication

\`\`\`bash
seclai auth login [--port <port>] [--no-browser]   # OAuth2 + PKCE in the browser
seclai auth status                                 # active profile's auth state
seclai auth refresh                                # refresh the token manually
seclai auth logout                                 # clear cached tokens
\`\`\`

Tokens are cached under the config directory and refreshed automatically, so
\`auth refresh\` is only needed to force it. An API key in \`SECLAI_API_KEY\` takes a
different path entirely and needs none of this.

## Profiles

\`\`\`bash
seclai configure sso [--profile-name <name>]   # interactive: domain, client ID, region, account ID
seclai configure list                          # every configured profile
\`\`\`

Profiles live in \`~/.seclai/config\` (override with \`--config-dir\` or
\`SECLAI_CONFIG_DIR\`). Select one per invocation with \`--profile <name>\`, or set
\`SECLAI_PROFILE\`.

## API version

\`\`\`bash
seclai api-version get           # what version does a request resolve to?
seclai api-version set <date>    # pin the account — affects every client
seclai api-version clear         # remove the pin
\`\`\`

\`set\` and \`clear\` change the account, not just this CLI. To affect only your own
invocation, use the \`--api-version\` global option instead.

## MCP server

\`\`\`bash
# write Seclai MCP server config into AI coding tool config files
seclai mcp configure --key <apiKey> [--target claude-code|cursor|claude-desktop|windsurf|all] [--dir .]

# print the config JSON for manual setup
seclai mcp show [--key <apiKey>]
\`\`\`

## Skill files

\`\`\`bash
# install these skill files into AI coding tool directories
seclai skills install [--tool copilot|claude|cursor|windsurf|codex|kiro|cline|roo|gemini|antigravity|all] [--dir .]
\`\`\`

With no \`--tool\`, the target is detected from the directory structure.

## Shell completion

\`\`\`bash
seclai completion bash   # eval "\$(seclai completion bash)" in ~/.bashrc
seclai completion zsh    # eval "\$(seclai completion zsh)" in ~/.zshrc
seclai completion fish   # seclai completion fish > ~/.config/fish/completions/seclai.fish
\`\`\`
` },
  { name: "references/solutions.md", content: `# Solutions and governance

Solutions group agents, knowledge bases and sources into one deliverable.
Governance defines the policies applied to agent input and output.

## Solutions

\`\`\`bash
seclai solutions list [--page N] [--limit N] [--sort field] [--order asc|desc]
seclai solutions create --json '{"name":"Customer Support Solution"}'
seclai solutions get <solutionId>
seclai solutions update <solutionId> --json '{"name":"Updated"}'
seclai solutions delete <solutionId>
\`\`\`

## Linking resources

\`\`\`bash
# each flag takes a JSON array of IDs
seclai solutions link <solutionId> --agents '["agentId1"]' --kb '["kbId1"]' --sources '["sourceId1"]'
seclai solutions unlink <solutionId> --agents '["agentId1"]'
\`\`\`

## Conversations

\`\`\`bash
seclai solutions convos list <solutionId>
seclai solutions convos add <solutionId> --json '{"message":"How should I structure this?"}'
seclai solutions convos mark <solutionId> <conversationId> --json '{"accepted":true}'
\`\`\`

## Solution AI

\`\`\`bash
seclai solutions ai generate <solutionId> --user-input "Add an FAQ source"
seclai solutions ai kb <solutionId> --user-input "Create a knowledge base for docs"
seclai solutions ai source <solutionId> --user-input "Create a file source for PDFs"
seclai solutions ai accept <solutionId> <conversationId> --json '{"accepted":true}'
seclai solutions ai decline <solutionId> <conversationId>
\`\`\`

\`ai kb\` and \`ai source\` create the resource and link it to the solution in one
step, which is why they live here rather than under \`kb\` or \`sources\`.

## Governance AI

\`\`\`bash
seclai governance ai generate --user-input "Create a content safety policy"
seclai governance ai list
seclai governance ai accept <conversationId>
seclai governance ai decline <conversationId>
\`\`\`

A generated policy is a proposal until accepted — \`generate\` alone changes
nothing.

## Example: solution with linked resources

\`\`\`bash
seclai solutions create --json '{"name":"Customer Support"}'
seclai solutions link <solutionId> --agents '["<agentId>"]' --kb '["<kbId>"]' --sources '["<sourceId>"]'
seclai solutions get <solutionId>
\`\`\`

## Example: governance policy setup

\`\`\`bash
seclai governance ai generate --user-input "Create a content safety policy that blocks harmful outputs"
seclai governance ai list
seclai governance ai accept <conversationId>
\`\`\`
` },
  { name: "references/streaming.md", content: `# Streaming Agent Runs

## Modes

### --stream
Wait for the agent run to complete via SSE. Prints the final result as a single JSON object.
Useful when you want to block until done.

\`\`\`bash
seclai agents run <agentId> --json '{"input":"Hello"}' --stream
seclai agents run <agentId> --json '{"input":"Hello"}' --stream --timeout-ms 120000
\`\`\`

### --events
Stream individual SSE events as NDJSON (one JSON object per line). Use for real-time processing.

\`\`\`bash
# all events, full event objects
seclai agents run <agentId> --json '{"input":"Hello"}' --events

# only data payloads (no event metadata)
seclai agents run <agentId> --json '{"input":"Hello"}' --events --output data

# only status events
seclai agents run <agentId> --json '{"input":"Hello"}' --events --output status

# filter specific event types
seclai agents run <agentId> --json '{"input":"Hello"}' --events --event-filter "status,data"
\`\`\`

Output modes for --events:
- \`full\`: entire SSE event object (default)
- \`data\`: only the data payload of each event
- \`status\`: only events with status information

### --poll
Poll the API at intervals for run completion. Does not use SSE.

\`\`\`bash
seclai agents run <agentId> --json '{"input":"Hello"}' --poll
seclai agents run <agentId> --json '{"input":"Hello"}' --poll --poll-interval-ms 5000 --include-step-outputs
\`\`\`

### No flag
Fire-and-forget: starts the run and immediately returns the run ID.

\`\`\`bash
seclai agents run <agentId> --json '{"input":"Hello"}'
# returns: {"id":"run_...","status":"queued",...}
# check later:
seclai agents runs get <runId>
\`\`\`
` },
  { name: "references/uploads.md", content: `# File Uploads & Content Management

## Upload to a source
\`\`\`bash
seclai sources upload <sourceId> --file ./doc.pdf
seclai sources upload <sourceId> --file ./doc.pdf --title "My Doc" --metadata '{"category":"docs"}' --file-name "custom-name.pdf" --mime-type "application/pdf"
seclai sources upload <sourceId> --file ./doc.pdf --metadata-file ./meta.json
\`\`\`

## Upload text directly
\`\`\`bash
seclai sources upload-text <sourceId> --json '{"text":"Article content here...","title":"My Article"}'
\`\`\`

## Upload input for agent runs
\`\`\`bash
# Check what files (if any) the agent expects before uploading. requires_uploads
# reports whether the agent accepts files; the agent block lists the exact names /
# indexes / patterns a run-time batch must satisfy.
seclai agents attachment-references <agentId>
seclai agents upload-input <agentId> --file ./input.pdf
seclai agents upload-input <agentId> --file ./data.csv --file-name "report.csv" --mime-type "text/csv"
seclai agents input-status <agentId> <uploadId>
\`\`\`

## Download an attachment emitted by a run
\`\`\`bash
# attachmentId is the URL-safe-base64 storage_key from run output manifests / webhooks.
seclai agents runs download-attachment <runId> <attachmentId> --output ./out.pdf
\`\`\`

## Replace content
\`\`\`bash
# replace with file
seclai contents upload <contentVersionId> --file ./updated.pdf

# replace with text
seclai contents replace-text <contentVersionId> --json '{"text":"Updated content","title":"Revised Article"}'
\`\`\`

## Read content
\`\`\`bash
# full content
seclai contents get <contentVersionId>

# text slice (0-based offsets)
seclai contents get <contentVersionId> --start 0 --end 1000

# view embeddings
seclai contents embeddings <contentVersionId> [--page N] [--limit N]
\`\`\`
` },
];
// END SKILL_FILES

// --- Tool detection & path mapping ---

type ToolConfig = {
  dir: string;
  files: Array<{ name: string; content: string }>;
};

function getToolConfig(tool: string, destDir: string): ToolConfig {
  // Generated from skills/seclai-cli/ by scripts/sync-skills.cjs — every file
  // found there ships, so adding a reference needs no change here.
  const skillFiles = SKILL_FILES;

  switch (tool) {
    case "copilot":
      return { dir: join(destDir, ".github", "copilot", "seclai-cli"), files: skillFiles };
    case "claude":
      return { dir: join(destDir, ".claude", "skills", "seclai-cli"), files: skillFiles };
    case "cursor":
      return { dir: join(destDir, ".cursor", "skills", "seclai-cli"), files: skillFiles };
    case "windsurf":
      return { dir: join(destDir, ".windsurf", "skills", "seclai-cli"), files: skillFiles };
    case "codex":
      return { dir: join(destDir, ".codex", "skills", "seclai-cli"), files: skillFiles };
    case "kiro":
      return { dir: join(destDir, ".kiro", "steering", "seclai-cli"), files: skillFiles };
    case "cline":
      return { dir: join(destDir, ".clinerules", "seclai-cli"), files: skillFiles };
    case "roo":
      return { dir: join(destDir, ".roo", "rules", "seclai-cli"), files: skillFiles };
    case "gemini":
      return { dir: join(destDir, ".gemini", "seclai-cli"), files: skillFiles };
    case "antigravity":
      return { dir: join(destDir, ".antigravity", "seclai-cli"), files: skillFiles };
    default:
      throw new Error(`Unknown tool: ${tool}. Use copilot, claude, cursor, windsurf, codex, kiro, cline, roo, gemini, or antigravity.`);
  }
}

function detectTools(destDir: string): string[] {
  const detected: string[] = [];

  if (existsSync(join(destDir, ".github", "copilot"))) detected.push("copilot");
  if (existsSync(join(destDir, ".claude")) || existsSync(join(destDir, "CLAUDE.md")))
    detected.push("claude");
  if (existsSync(join(destDir, ".cursor"))) detected.push("cursor");
  if (existsSync(join(destDir, ".windsurf"))) detected.push("windsurf");
  if (existsSync(join(destDir, ".codex"))) detected.push("codex");
  if (existsSync(join(destDir, ".kiro"))) detected.push("kiro");
  if (existsSync(join(destDir, ".clinerules")) && statSync(join(destDir, ".clinerules")).isDirectory()) detected.push("cline");
  if (existsSync(join(destDir, ".roo"))) detected.push("roo");
  if (existsSync(join(destDir, ".gemini")) || existsSync(join(destDir, "GEMINI.md")))
    detected.push("gemini");
  if (existsSync(join(destDir, ".antigravity"))) detected.push("antigravity");

  return detected;
}

/** Register the `skills` command for installing Seclai skill files into AI coding tool directories. */
export function register(program: Command, rt: CliRuntime): void {
  const skills = program.command("skills").description("Install Seclai CLI skill files for AI coding tools.");

  skills
    .command("install")
    .description(
      "Write Seclai CLI skill/instruction files into the current workspace.\n\n" +
        "Detected tools: copilot, claude, cursor, windsurf, codex, kiro, cline, roo, gemini, antigravity.\n" +
        "Use --tool to target a specific tool, or 'all' for all supported tools."
    )
    .option("--tool <name>", "Target tool (copilot|claude|cursor|windsurf|codex|kiro|cline|roo|gemini|antigravity|all). Auto-detects if omitted.")
    .option("--dir <path>", "Target directory (default: current directory).", ".")
    .action(async (opts) => {
      await run(rt, async () => {
        const destDir = opts.dir;
        let tools: string[];

        if (opts.tool === "all") {
          tools = ["copilot", "claude", "cursor", "windsurf", "codex", "kiro", "cline", "roo", "gemini", "antigravity"];
        } else if (opts.tool) {
          tools = [opts.tool];
        } else {
          tools = detectTools(destDir);
          if (tools.length === 0) {
            tools = ["copilot"]; // default fallback
            rt.writeErr("No AI tool detected, defaulting to copilot.\n");
          }
        }

        let totalFiles = 0;
        for (const tool of tools) {
          const config = getToolConfig(tool, destDir);
          for (const file of config.files) {
            const filePath = join(config.dir, file.name);
            await mkdir(dirname(filePath), { recursive: true });
            await writeFile(filePath, file.content, "utf8");
            totalFiles++;
          }
          rt.writeErr(`Installed ${config.files.length} skill files for ${tool} → ${config.dir}\n`);
        }

        printJson(rt, { ok: true, tools, filesWritten: totalFiles });
      });
    });
}
