// Regenerate the skill content compiled into src/commands/skills.ts from the
// files under skills/seclai-cli/.
//
// `seclai skills install` writes string constants, not the files on disk, so
// editing skills/ alone changes nothing that ships. This script is the bridge,
// and tests/drift.test.ts fails the build when the two diverge. `pretest` runs
// it, so the two cannot drift in a working tree that runs its own tests.
//
// The file list is discovered, and discovered recursively: an early version
// named four files explicitly, and its replacement matched only
// `references/*.md` at one level — both would silently ship nothing for a file
// that did not fit the shape they assumed.
const fs = require("fs");
const path = require("path");

// Resolved from this file, not the process cwd, so the script behaves the same
// wherever it is invoked from — tests/drift.test.ts already anchors this way.
const REPO_ROOT = path.resolve(__dirname, "..");
const SKILL_DIR = path.join(REPO_ROOT, "skills", "seclai-cli");
const TARGET = path.join(REPO_ROOT, "src", "commands", "skills.ts");
// Unique, whole-line sentinels rather than incidental substrings. The previous
// pair — `const SKILL_FILES` and `// --- Tool detection` — were short enough to
// plausibly appear inside the very markdown they delimit, and `// --- Tool
// detection` doubled as a human section heading, so renaming that heading would
// silently break the generator.
const MARKER_START = "// BEGIN SKILL_FILES";
const MARKER_END = "// END SKILL_FILES";
const BANNER =
  "// BEGIN SKILL_FILES — generated by scripts/sync-skills.cjs. Do not edit by hand;\n" +
  "// edit skills/seclai-cli/ and run `npm run sync:skills`.\n";

const fail = (message) => {
  console.error(message);
  process.exit(1);
};

/**
 * Every markdown file under the skill directory, relative to it, with SKILL.md
 * first and the rest sorted so output is stable.
 *
 * Recursive and shape-agnostic: a new top-level file or a nested reference is
 * picked up without touching this script. `withFileTypes` keeps a directory
 * named `something.md` from reaching readFileSync and aborting with EISDIR.
 */
function collect(dir = SKILL_DIR, prefix = "") {
  const found = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) found.push(...collect(path.join(dir, entry.name), rel));
    else if (entry.isFile() && entry.name.endsWith(".md")) found.push(rel);
  }
  return prefix === ""
    ? [...found.filter((f) => f === "SKILL.md"), ...found.filter((f) => f !== "SKILL.md").sort()]
    : found;
}

/** Escape for embedding inside a JS template literal. */
function escapeForTemplate(s) {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

if (!fs.existsSync(SKILL_DIR)) fail(`Skill directory not found: ${SKILL_DIR}`);

const names = collect();
if (!names.includes("SKILL.md")) fail(`No SKILL.md in ${SKILL_DIR}`);

// Checked before anything is written. The previous version tested only the file
// as it already was, so a skill file containing marker text embedded cleanly on
// the first run and bricked every run after it — with the offending text now on
// both sides of the check and no way to regenerate.
for (const name of names) {
  const body = fs.readFileSync(path.join(SKILL_DIR, name), "utf8");
  for (const marker of [MARKER_START, MARKER_END]) {
    if (body.includes(marker)) {
      fail(
        `${SKILL_DIR}/${name} contains the generator marker "${marker}". ` +
          `Embedding it would make src/commands/skills.ts unparseable on the next run. ` +
          `Reword that line, or change the markers in this script.`,
      );
    }
  }
}

const entries = names
  .map((name) => {
    const body = fs.readFileSync(path.join(SKILL_DIR, name), "utf8");
    return `  { name: ${JSON.stringify(name)}, content: \`${escapeForTemplate(body)}\` },`;
  })
  .join("\n");

const replacement =
  BANNER +
  "const SKILL_FILES: Array<{ name: string; content: string }> = [\n" +
  entries +
  "\n];\n" +
  MARKER_END;

let code = fs.readFileSync(TARGET, "utf8");

/** Offset of `marker`, and whether a second occurrence exists. */
function locate(text, marker) {
  const index = text.indexOf(marker);
  if (index === -1) return { index, duplicate: false };
  return { index, duplicate: text.indexOf(marker, index + marker.length) !== -1 };
}

const start = locate(code, MARKER_START);
const end = locate(code, MARKER_END);

if (start.index === -1 || end.index === -1) {
  fail(
    `Could not find both markers in ${TARGET}. ` +
      `"${MARKER_START}": ${start.index === -1 ? "missing" : "found"}, ` +
      `"${MARKER_END}": ${end.index === -1 ? "missing" : "found"}`,
  );
}
if (start.duplicate || end.duplicate) {
  fail(
    `Ambiguous markers in ${TARGET} — splicing would cut at the wrong offset. ` +
      `Regenerate from a clean checkout of that file.`,
  );
}
if (end.index <= start.index) {
  fail(`Markers out of order in ${TARGET}: "${MARKER_END}" precedes "${MARKER_START}".`);
}

// End marker is consumed and re-emitted, so the banner and both sentinels stay
// exactly one line each no matter how often this runs.
code = code.substring(0, start.index) + replacement + code.substring(end.index + MARKER_END.length);
fs.writeFileSync(TARGET, code, "utf8");
console.log(`Regenerated ${names.length} skill files into src/commands/skills.ts:`);
for (const n of names) console.log(`  ${n}`);
